### PR TITLE
Installation

### PR DESCRIPTION
**Pull request by Valentine-Mario**

### CODE REVIEW

**Comment by arctic-hen7** [comment]
What exactly does this do?

**Comment by arctic-hen7** [comment]
Doesn't this still just install a NodeJS package directly?

**Comment by arctic-hen7** [comment]
@Valentine-Mario this looks identical to #5, could you please confirm that? If so, I'm afraid I'll have to close it for the reasons I specified there.

**Comment by Valentine-Mario** [comment]
> @Valentine-Mario this looks identical to #5, could you please confirm that? If so, I'm afraid I'll have to close it for the reasons I specified there.

Yes. It is. Please close it.

**Comment by arctic-hen7** [comment]
Understood. Thank you very much for the confirmation!

**Pull request closed without merging**
